spring.application.name=Actividad_Torres

# SERVER
server.port=8083
server.compression.enabled=true

# LOGGING
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/gestor-inventario.log

# JSON
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# SECURITY
spring.security.user.name=admin
spring.security.user.password=inventario123

# BASE DE DATOS


info.app.name=Gestor de Inventario
info.app.description=API de gestion de inventario
info.app.version=@project.version@

# APP INFO
app.info.name=Gestor de Inventario
app.info.version=@project.version@
app.info.developer.name=Lisseth
app.info.developer.email=jltorres15@espe.edu.ec